stages:
  - build

build-job:
  stage: build
  script:
    - nix run nixpkgs/nixpkgs-unstable#nix-eval-jobs -- --workers 4 --gc-roots-dir $(pwd)/gcroot --flake '.#hydraJobs' > jobs
    - nix run nixpkgs/nixpkgs-unstable#jq -- -r '.drvPath' < jobs | xargs nix build -L
