name: "CI"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v14
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210604_8e6ee1b/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            system-features = nixos-test benchmark big-parallel kvm recursive-nix

      - name: Run Flake Check
        run: nix -Lv flake check

      - name: Run Flake Show
        run: nix -Lv flake show

      - name: Build photoprism
        run: nix -Lv build .#photoprism
      - name: Check photoprism Exec
        run: nix run ./#photoprism -- --help
